#!/bin/bash

## REPO SPECIFIC DIRECTORIES
GIT_DIR=.git
HG_DIR=.hg
SVN_DIR=.svn

## COUNTERS
GIT_COUNT=0
HG_COUNT=0
SVN_COUNT=0

## USAGE FUNCTION
function usage
{
    printf "Usage: $0 list-of-directories\n"
}

## REPO TESTING FUNCTION DEFINITIONS
# $1: VCS special hidden directory
# $2: directory where the repository is thought to be
function isRepoType
{
    if [[ $# -eq 0 ]];
    then
        false
        return
    fi

    if [[ $# -eq 1 ]];
    then
        DIR=.
    else
        DIR=$2
    fi

    [[ -d ${DIR}/$1 ]];
}

# $1: directory
function isGit
{
    isRepoType ${GIT_DIR} $1
}

# $1: directory
function isHg
{
    isRepoType ${HG_DIR} $1
}

# $1: directory
function isSvn
{
    isRepoType ${SVN_DIR} $1
}

## REPO UPDATE FUNCTION DEFINITIONS

# $1: repository directory
# $2: vcs name
# $3: vcs counter
# $4: vcs update command
function updateRepo
{
    if [[ $# -eq 0 ]];
    then
        false
        return
    fi

    OLD_PATH=$(pwd)
	printf "    Updating %s repository %s...\n" $2 $1
	cd $1
	printf "    "
	eval $4
	((++$3))
    printf "\n"
    cd ${OLD_PATH}
}

function updateGit
{
    updateRepo $1 git GIT_COUNT "git pull"
}

function updateHg
{
    updateRepo $1 hg HG_COUNT "hg pull"
}

function updateSvn
{
    updateRepo $1 svn SVN_COUNT "svn update"
}

## SCRIPT BODY
if [[ $# -eq 0 ]]
then
    usage
    exit 1
fi

printf "Updating repositories...\n"
for UPPER_DIR in $@
do
    cd ${UPPER_DIR}
    DIRS=$(ls -Ad */)

    for DIR in ${DIRS}
    do
        if isGit ${DIR};
        then
            updateGit ${DIR}
        elif isHg ${DIR};
        then
            updateHg ${DIR}
        elif isSvn ${DIR};
        then
            updateSvn ${DIR}
        fi
    done
done

printf "%s Git repositories updated\n" ${GIT_COUNT}
printf "%s Hg repositories updated\n" ${HG_COUNT}
printf "%s Svn repositories updated\n" ${SVN_COUNT}
printf "\n"
printf "Done\n"
exit 0
